### ISSUE TITLE
Using a pinned SSL Certificate

### ISSUE THREAD

**Issue by PWani** [acmacalister/jetfire#1]
Is there some way to use a pinned SSL certificate?  If there were a way to pass a URL request rather than a URL to init, this could be just handled by CFStream.  i.e. with Socket Rocket I used to  do something like:

        NSURL *url = [NSURL URLWithString: ServerSocketURLString];
        NSMutableURLRequest *request = [[NSMutableURLRequest alloc] initWithURL:url];
        
        NSString *cerPath = [[NSBundle mainBundle] pathForResource:@"servercertificate" ofType:@"cer"];
        NSData *certData = [[NSData alloc] initWithContentsOfFile:cerPath];
        CFDataRef certDataRef = (__bridge CFDataRef)certData;
        SecCertificateRef certRef = SecCertificateCreateWithData(NULL, certDataRef);
        id certificate = (__bridge id)certRef;
        
        [request setSR_SSLPinnedCertificates:@[certificate]];
        
        self.socket = [[JFWebSocket alloc] initWithURLRequest:request];
        
        self.socket.delegate = self;

Thanks!

**Comment by acmacalister** [comment]
I started work on this in 0.1.4. Hopefully should have some for the 0.1.5 update.

**Comment by daltoniam** [comment]
This has been added.
https://github.com/acmacalister/jetfire#ssl-pinning

**Comment by mixdux** [comment]
I just lost two hours while trying to implement pinned certificate - the problem was not in the library but the certificate file itself, PWani's code might be misleading as just minutes ago I figured that in my case
```obj-c
SecCertificateRef certRef = SecCertificateCreateWithData(NULL, certDataRef);
//(app crashes on an implementation of SecCertificateCreateWithData in JFRSecurity.m)
```
could only make valid certRef object if the original certificate was **DER** encoded. This might save somenone else's time, Jetfire is alas not making any problems for self signed certificates. Cheers!

**Comment by acmacalister** [comment]
@mixdux thanks for the feedback. I will make a note of that in the README as well.
